spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:15432/server_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true
    drop-first: false
    default-schema: public
  servlet:
    multipart:
      maxFileSize: 10485760
      maxRequestSize: 10485760

minio:
  url: http://localhost:9000
  port: 9000
  access-key: user
  secret-key: password
  secure: false
  bucket: minio-storage
  image-size: 10485760

server:
  port: 8080

logging:
  level:
    liquibase: info

springdoc:
  swagger-ui:
    path: /swagger.html

application:
  auth:
    jwt:
      secret-key: AC13E9DC05A0195C9FE3CC6BC81E4729A20AC2DF0AD680A4FAD3D3F961C07F72
      expiration-timeout-milliseconds: 86400000
