spring:
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: false
    drop-first: false
    default-schema: public

  kafka:
    listener.ack-mode: manual
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
  cloud:
    zookeeper:
      config.enabled: false
      connect-string: localhost:2181

minio:
  url: http://localhost:9000
  port: 9000
  access-key: user
  secret-key: password
  secure: false
  bucket: minio-storage
  image-size: 10485760

server:
  port: 8081

logging:
  level:
    liquibase: info

application:
  kafka:
    topic-wip: images.wip
    topic-done: images.done
    partitions: 3
    replicas: 3
    group-id: custom-group-id